# Generated by Django 4.2.7 on 2025-09-23 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, verbose_name='نظرات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ارزیابی کارمند',
                'verbose_name_plural': 'ارزیابی\u200cهای کارمند',
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام معیار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('weight', models.FloatField(default=1.0, verbose_name='وزن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'معیار ارزیابی',
                'verbose_name_plural': 'معیارهای ارزیابی',
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='امتیاز')),
                ('comments', models.TextField(blank=True, verbose_name='نظرات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.employeeevaluation', verbose_name='ارزیابی')),
                ('scored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_scores', to=settings.AUTH_USER_MODEL, verbose_name='امتیازدهنده')),
            ],
            options={
                'verbose_name': 'امتیاز ارزیابی',
                'verbose_name_plural': 'امتیازات ارزیابی',
            },
        ),
        migrations.AddField(
            model_name='employeeevaluation',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.evaluationcriteria', verbose_name='معیار'),
        ),
        migrations.AddField(
            model_name='employeeevaluation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
        migrations.AddField(
            model_name='employeeevaluation',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='ارزیاب'),
        ),
    ]
