# Generated by Django 5.2.6 on 2025-09-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='participations/%Y/%m/%d/', verbose_name='پیوست'),
        ),
    ]
