# Generated by Django 5.2.6 on 2025-09-30 05:04

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_participation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=users.models.participation_upload_path, verbose_name='پیوست'),
        ),
    ]
