# Generated by Django 5.2.6 on 2025-10-21 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_participation_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.factory', verbose_name='کارخانه'),
        ),
        migrations.AddField(
            model_name='permissionlevel',
            name='can_access_all_factories',
            field=models.BooleanField(default=False, verbose_name='دسترسی به همه کارخانه\u200cها'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='feedback',
            field=models.TextField(default='بدون فیدبک', verbose_name='فیدبک رد شدن'),
        ),
    ]
