# Generated by Django 5.2.6 on 2025-10-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_participation_summarized_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='orginal_content',
            field=models.TextField(blank=True, null=True, verbose_name='متن اصلی استخراج شده'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
    ]
