# Generated by Django 5.2.6 on 2025-10-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_employee_day_usage_employee_last_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه دستگاه (IP)'),
        ),
    ]
