# Generated by Django 5.2.6 on 2025-11-05 06:45

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_factory_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='role_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نقش کاربر'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=users.models.participation_upload_path, verbose_name='پیوست'),
        ),
    ]
