# Generated by Django 5.2.6 on 2025-11-12 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_participation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='linked_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.factory', verbose_name='کارخانه لینک شده'),
        ),
    ]
