# Generated by Django 5.2.6 on 2025-11-12 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_factory_linked_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='linked_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department', verbose_name='کارخانه لینک شده'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='linked_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subdepartment', verbose_name='کارخانه لینک شده'),
        ),
    ]
