# Generated by Django 5.2.6 on 2025-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_participation_department_committee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='manager_1_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت مدیر کمیته 1'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_2_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت مدیر کمیته 2'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_3_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت مدیر کمیته 3'),
        ),
        migrations.AddField(
            model_name='participation',
            name='supervisor_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت سرپرست کمیته'),
        ),
    ]
