# Generated by Django 5.2.6 on 2025-11-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_rename_personnel_code_employee_personnel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, verbose_name='وضعیت'),
        ),
    ]
