# Generated by Django 5.2.6 on 2025-11-20 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_department_is_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام غذا')),
                ('default_price', models.PositiveIntegerField(default=0, verbose_name='قیمت پیش\u200cفرض (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'بانک غذاها',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_restaurant',
        ),
        migrations.AddField(
            model_name='department',
            name='is_self',
            field=models.BooleanField(default=False, verbose_name='سلف است؟'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='is_restaurant',
            field=models.BooleanField(default=False, verbose_name='رستوران سلف است؟'),
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='شروع هفته (شنبه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='منوی فعال')),
                ('restaurant', models.ForeignKey(limit_choices_to={'is_restaurant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_menus', to='users.subdepartment', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'منوی هفتگی',
                'verbose_name_plural': 'منوهای هفتگی',
                'unique_together': {('restaurant', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_persian', models.CharField(choices=[('shanbe', 'شنبه'), ('1shanbe', 'یکشنبه'), ('2shanbe', 'دوشنبه'), ('3shanbe', 'سه\u200cشنبه'), ('4shanbe', 'چهارشنبه'), ('5shanbe', 'پنج\u200cشنبه'), ('jome', 'جمعه')], max_length=10, verbose_name='روز هفته')),
                ('food_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام غذا')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (ریال)')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('weekly_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.weeklymenu')),
            ],
            options={
                'verbose_name': 'غذای منو',
                'verbose_name_plural': 'غذاهای منو',
                'unique_together': {('weekly_menu', 'day_persian', 'food_name')},
            },
        ),
        migrations.CreateModel(
            name='FoodReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(db_index=True, verbose_name='تاریخ رزرو')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('is_canceled', models.BooleanField(default=False, verbose_name='لغو شده')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_reservations', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.menuitem')),
            ],
            options={
                'verbose_name': 'رزرو غذا',
                'verbose_name_plural': 'رزروهای غذا',
                'unique_together': {('employee', 'reservation_date')},
            },
        ),
    ]
