# Generated by Django 5.2.6 on 2025-11-20 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_fooditem_remove_department_is_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.fooditem', verbose_name='غذا'),
        ),
    ]
