# Generated by Django 5.2.6 on 2025-11-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='food_name',
        ),
    ]
