# Generated by Django 5.2.6 on 2025-11-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_fooditem_real_price_alter_fooditem_default_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodreservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='is_quota_used',
            field=models.BooleanField(default=False, verbose_name='استفاده از سهمیه'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد سفارش'),
        ),
    ]
