# Generated by Django 5.2.6 on 2025-11-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_participation_return_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='return_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دفعات برگردانده  شده'),
        ),
    ]
