# Generated by Django 5.2.6 on 2025-11-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_participation_return_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_audio',
            field=models.BooleanField(default=False, verbose_name='فایل قابل تبدیل به متن است؟'),
        ),
    ]
