# Generated by Django 5.2.6 on 2025-12-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_foodreservation_feedback_foodreservation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_food_receiver',
            field=models.BooleanField(default=False, verbose_name='تحویل گیرنده غذا'),
        ),
    ]
