# Generated by Django 5.2.6 on 2025-12-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_employee_food_receiver_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='تحویل شده؟'),
        ),
    ]
