# Generated by Django 5.2.6 on 2025-12-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_foodreservation_total_price_at_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodreservation',
            name='total_price_at_reservation',
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='final_price_at_reservation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل در لحظه رزرو'),
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='unit_price_at_reservation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت واحد در لحظه رزرو'),
        ),
    ]
