# Generated by Django 5.2.6 on 2025-12-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_remove_foodreservation_final_price_at_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodreservation',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='guest',
        ),
    ]
