# Generated by Django 5.2.6 on 2025-12-13 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_orgunit_referral_referralstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='unit_type',
            field=models.CharField(choices=[('system', 'سیستم'), ('holding', 'هلدینگ'), ('factory', 'کارخانه'), ('department', 'بخش'), ('subdepartment', 'زیربخش'), ('employee', 'پرسنل')], max_length=20),
        ),
    ]
