# Generated by Django 5.2.6 on 2025-12-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_orgunit_employee_alter_orgunit_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgunit',
            name='employee',
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='unit_type',
            field=models.CharField(choices=[('holding', 'هلدینگ'), ('factory', 'کارخانه'), ('department', 'بخش'), ('subdepartment', 'زیربخش')], max_length=20),
        ),
    ]
