# Generated by Django 5.2.6 on 2025-12-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_employee_unlimit_reservation_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='unlimit_reservation',
        ),
    ]
