# Generated by Django 4.2.7 on 2025-09-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_access_all_departments',
            field=models.BooleanField(default=False),
        ),
    ]
