# Generated by Django 4.2.7 on 2025-09-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'مدیر کل'), ('department_manager', 'مدیر بخش'), ('supervisor', 'سرپرست'), ('employee', 'پرسنل')], max_length=50, unique=True, verbose_name='نام نقش'),
        ),
    ]
