# Generated by Django 5.2.6 on 2025-09-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_participation_feedback_participation_is_finalized_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={},
        ),
        migrations.AlterField(
            model_name='participation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='participations/%Y/%m/%d', verbose_name='پیوست'),
        ),
    ]
