# Generated by Django 5.2.6 on 2025-10-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_participation_count_sumerized'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='day_usage',
            field=models.IntegerField(default=0, verbose_name='حجم استفاده اخرین روز'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_file_upload',
            field=models.DateTimeField(null=True, verbose_name='تاریخ اخرین اپلود'),
        ),
    ]
