# Generated by Django 5.2.6 on 2025-10-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_employee_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mac_address',
        ),
    ]
