# Generated by Django 5.2.6 on 2025-11-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_employee_role_employee_roles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'مشارکت', 'verbose_name_plural': 'مشارکت\u200cها'},
        ),
        migrations.AddField(
            model_name='participation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department', verbose_name='بخش مرتبط'),
        ),
        migrations.AddField(
            model_name='participation',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.holding', verbose_name='هلدینگ مرتبط'),
        ),
        migrations.AddField(
            model_name='participation',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subdepartment', verbose_name='زیربخش مرتبط'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.factory', verbose_name='کارخانه'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.factory', verbose_name='کارخانه مرتبط'),
        ),
    ]
