# Generated by Django 5.2.6 on 2025-11-01 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_participation_options_participation_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_factories', to=settings.AUTH_USER_MODEL, verbose_name='مدیر کارخانه'),
        ),
    ]
