# Generated by Django 5.2.6 on 2025-11-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_participation_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='holding',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='subdepartment',
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_subdepartments',
            field=models.ManyToManyField(blank=True, related_name='assigned_employees', to='users.subdepartment', verbose_name='زیربخش\u200cهای تخصیص\u200cیافته'),
        ),
    ]
