# Generated by Django 5.2.6 on 2025-11-12 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_employee_department_remove_employee_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='کمیته است؟'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_managed_departments_2', to=settings.AUTH_USER_MODEL, verbose_name='مدیر دوم'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_managed_departments_3', to=settings.AUTH_USER_MODEL, verbose_name='مدیر سوم'),
        ),
        migrations.AddField(
            model_name='factory',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='کمیته است؟'),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='کمیته است؟'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_1_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='نظر مدیر اول'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_2_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='نظر مدیر دوم'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_3_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='نظر مدیر سوم'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='کمیته است؟'),
        ),
    ]
