# Generated by Django 5.2.6 on 2025-11-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_department_is_committee_department_manager_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
    ]
