# Generated by Django 5.2.6 on 2025-11-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_department_linked_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='department_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_department_participations', to='users.department', verbose_name='بخش کمیته مرتبط'),
        ),
        migrations.AddField(
            model_name='participation',
            name='factory_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_factory_participations', to='users.factory', verbose_name='کارخانه کمیته مرتبط'),
        ),
        migrations.AddField(
            model_name='participation',
            name='holding_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_participations', to='users.holding', verbose_name='هلدینگ کمیته مرتبط'),
        ),
        migrations.AddField(
            model_name='participation',
            name='subdepartment_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_subdepartment_participations', to='users.subdepartment', verbose_name='زیربخش کمیته مرتبط'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_participations', to='users.department', verbose_name='بخش مرتبط'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_participations', to='users.factory', verbose_name='کارخانه مرتبط'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='users.holding', verbose_name='هلدینگ مرتبط'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartment_participations', to='users.subdepartment', verbose_name='زیربخش مرتبط'),
        ),
    ]
