# Generated by Django 5.2.6 on 2025-11-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_participation_manager_1_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='supervisor_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='نظر سرپرست'),
        ),
    ]
