# Generated by Django 5.2.6 on 2025-11-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_participation_supervisor_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='manager_1_feedback',
            new_name='manager_feedback',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='manager_1_status',
            new_name='manager_status',
        ),
    ]
