# Generated by Django 5.2.6 on 2025-11-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_rename_manager_1_feedback_participation_manager_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartment',
            name='linked_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.factory', verbose_name='کارخانه لینک شده'),
        ),
    ]
