# Generated by Django 5.2.6 on 2025-11-17 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_employee_personnel_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Personnel_code',
            new_name='personnel_code',
        ),
    ]
