# Generated by Django 5.2.6 on 2025-11-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_participation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_restaurant',
            field=models.BooleanField(default=False, verbose_name='رستوران (سلف) است؟'),
        ),
    ]
