# Generated by Django 5.2.6 on 2025-11-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_menuitem_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
    ]
