# Generated by Django 5.2.6 on 2025-11-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_remove_menuitem_food_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'غذای منو', 'verbose_name_plural': 'غذاهای منو'},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('weekly_menu', 'food', 'day_persian')},
        ),
    ]
