# Generated by Django 5.2.6 on 2025-11-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='real_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت آزاد'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='default_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت کارخانه'),
        ),
    ]
