# Generated by Django 5.2.6 on 2025-11-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_foodreservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='related_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.factory', verbose_name='کارخانه'),
        ),
    ]
