# Generated by Django 5.2.6 on 2025-11-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_foodreservation_related_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='return_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد دفعات برگردانده  شده'),
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='related_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.factory', verbose_name='کارخانه'),
        ),
    ]
