# Generated by Django 5.2.6 on 2025-11-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_participation_is_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='feedback',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='نظر و پیشنهاد'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='امتیاز (۱ تا ۵ ستاره)'),
        ),
    ]
