# Generated by Django 5.2.6 on 2025-12-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_employee_is_food_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_food_receiver',
        ),
    ]
