# Generated by Django 5.2.6 on 2025-12-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_remove_employee_is_food_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='food_receiver_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_food_receivers', to='users.factory', verbose_name='کارخانه تحویل\u200cگیرنده'),
        ),
        migrations.AddField(
            model_name='employee',
            name='food_receiver_holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_food_receivers', to='users.holding', verbose_name='هلدینگ تحویل\u200cگیرنده'),
        ),
        migrations.AddField(
            model_name='employee',
            name='food_receiver_role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'عادی'), (1, 'تحویل گیرنده کارخانه'), (2, 'تحویل گیرنده هلدینگ')], default=0, verbose_name='نقش تحویل\u200cگیرنده غذا'),
        ),
    ]
