# Generated by Django 5.2.6 on 2025-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_employee_food_receiver_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='food_receiver_role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'تحویل گیرنده نیست'), (1, 'تحویل گیرنده کارخانه'), (2, 'تحویل گیرنده هلدینگ')], default=0, verbose_name='نقش تحویل\u200cگیرنده غذا'),
        ),
    ]
