# Generated by Django 5.2.6 on 2025-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_foodreservation_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='guest',
            field=models.BooleanField(default=False, verbose_name='مهمان'),
        ),
    ]
