# Generated by Django 5.2.6 on 2025-12-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_foodreservation_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='total_price_at_reservation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل در زمان رزرو'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='unit_price_at_reservation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت واحد در زمان رزرو'),
        ),
    ]
