# Generated by Django 5.2.6 on 2025-12-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_remove_foodreservation_total_price_at_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodreservation',
            name='final_price_at_reservation',
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='unit_price_at_reservation',
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی رزرو'),
        ),
    ]
