# Generated by Django 5.2.6 on 2025-12-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_referral_referralstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralstep',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='referralstep',
            name='from_role',
        ),
        migrations.RemoveField(
            model_name='referralstep',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='referralstep',
            name='to_department',
        ),
        migrations.RemoveField(
            model_name='referralstep',
            name='to_factory',
        ),
        migrations.RemoveField(
            model_name='referralstep',
            name='to_holding',
        ),
        migrations.RemoveField(
            model_name='referralstep',
            name='to_role',
        ),
        migrations.RemoveField(
            model_name='referralstep',
            name='to_subdepartment',
        ),
        migrations.RemoveField(
            model_name='referralstep',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='ReferralStep',
        ),
    ]
