# Generated by Django 5.2.6 on 2025-12-15 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_remove_orgunit_employee_alter_orgunit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='unlimit_reservation',
            field=models.BooleanField(default=True, verbose_name='مجوز رزرو نامحدود'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اعلان')),
                ('description', models.TextField(verbose_name='توضیحات اعلان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('employee_subdepartments', models.ManyToManyField(blank=True, related_name='employee_targeted_notifications', to='users.subdepartment', verbose_name='زیربخش\u200cهای پرسنل (پرسنل کدام زیربخش\u200cها ببینند - فقط نقش employee)')),
                ('target_departments', models.ManyToManyField(blank=True, related_name='targeted_notifications', to='users.department', verbose_name='بخش\u200cهای هدف (از کارخانه\u200cهای انتخابی)')),
                ('target_factories', models.ManyToManyField(blank=True, related_name='targeted_notifications', to='users.factory', verbose_name='کارخانه\u200cهای هدف (از هلدینگ\u200cهای انتخابی)')),
                ('target_holdings', models.ManyToManyField(blank=True, related_name='targeted_notifications', to='users.holding', verbose_name='هلدینگ\u200cهای هدف (فقط هلدینگ\u200cهای مجاز)')),
                ('target_roles', models.ManyToManyField(related_name='targeted_notifications', to='users.role', verbose_name='نقش\u200cهای هدف (چه کسانی ببینند)')),
                ('target_subdepartments', models.ManyToManyField(blank=True, related_name='targeted_notifications', to='users.subdepartment', verbose_name='زیربخش\u200cهای هدف (از بخش\u200cهای انتخابی)')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='users.notification')),
            ],
            options={
                'verbose_name': 'خواندن اعلان',
                'verbose_name_plural': 'خواندن اعلانات',
                'unique_together': {('notification', 'employee')},
            },
        ),
    ]
