# Generated by Django 5.2.6 on 2025-12-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_remove_employee_unlimit_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='unlimit_reservation',
            field=models.BooleanField(default=False, verbose_name='مجوز رزرو نامحدود'),
        ),
    ]
