# Generated by Django 5.2.6 on 2025-12-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_banks_country_dependencystatus_employmenttype_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد نوع حساب')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع حساب بانکی')),
            ],
            options={
                'verbose_name': 'نوع حساب بانکی',
                'verbose_name_plural': 'نوع حساب های بانکی',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.bankaccounttype', verbose_name='نوع حساب بانکی'),
        ),
    ]
