# Generated by Django 5.2.6 on 2025-12-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_previousinsurer_employee_father_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_bimeh',
            name='insurance_type',
        ),
        migrations.DeleteModel(
            name='InsuranceType',
        ),
    ]
