# Generated by Django 5.2.6 on 2025-12-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_remove_employee_bimeh_insurance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=10, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='شماره شبا'),
        ),
    ]
