# Generated by Django 5.2.6 on 2025-12-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobgroup',
            old_name='title',
            new_name='name',
        ),
    ]
