# Generated by Django 5.2.6 on 2025-12-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_serve_foods',
            field=models.BooleanField(default=False, verbose_name='اجازه سرو غذا'),
        ),
    ]
