# Generated by Django 5.2.6 on 2025-12-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_employee_can_serve_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام غذا'),
        ),
    ]
