# Generated by Django 5.2.6 on 2026-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_fooditem_is_management_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_reserve_management_food',
            field=models.BooleanField(default=False, verbose_name='اجازه سفارش غذای ویژه'),
        ),
    ]
