# Generated by Django 5.2.6 on 2026-02-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_employee_can_reserve_management_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_reserve_for_others',
            field=models.BooleanField(default=False, verbose_name='مجوز رزرو برای دیگران'),
        ),
        migrations.AddField(
            model_name='employee',
            name='factory_limit_reservation_for_others',
            field=models.IntegerField(default=0, verbose_name='محدودیت رزرو سهمیه ای برای دیگران'),
        ),
        migrations.AddField(
            model_name='employee',
            name='free_limit_reservation_for_others',
            field=models.IntegerField(default=0, verbose_name='محدودیت رزرو آزاد برای دیگران'),
        ),
        migrations.AddField(
            model_name='employee',
            name='guest_limit_reservation_for_others',
            field=models.IntegerField(default=0, verbose_name='محدودیت رزرو مهمان برای دیگران'),
        ),
    ]
