# Generated by Django 5.2.6 on 2026-02-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_employee_can_reserve_for_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='reserved_by',
            field=models.PositiveIntegerField(default=0, verbose_name='شخص رزرو کننده (اگر خود یوزر بود، میشود 0)'),
        ),
    ]
