# Generated by Django 5.2.6 on 2026-02-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_foodreservation_reserved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='close_food_res_time_H',
            field=models.IntegerField(default=10, verbose_name='ساعت بسته شدن مهلت رزرو غذا در این کارخانه'),
        ),
        migrations.AddField(
            model_name='factory',
            name='close_food_res_time_M',
            field=models.IntegerField(default=0, verbose_name='دقیقه بسته شدن مهلت رزرو غذا در این کارخانه'),
        ),
    ]
