# Generated by Django 5.2.6 on 2026-02-25 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_factory_close_food_res_time_h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_departments_m2m', to=settings.AUTH_USER_MODEL, verbose_name='مدیران بخش'),
        ),
        migrations.AddField(
            model_name='factory',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_factories_m2m', to=settings.AUTH_USER_MODEL, verbose_name='مدیران کارخانه'),
        ),
        migrations.AddField(
            model_name='holding',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_holdings_m2m', to=settings.AUTH_USER_MODEL, verbose_name='مدیران هلدینگ'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_subdepartments_m2m', to=settings.AUTH_USER_MODEL, verbose_name='سرپرستان زیربخش'),
        ),
    ]
