# Generated by Django 5.2.6 on 2026-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_department_managers_factory_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manage_departments_members',
            field=models.ManyToManyField(blank=True, related_name='manage_departments_members', to='users.holding', verbose_name='مدیریت افراد این بخش ها'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manage_factories_members',
            field=models.ManyToManyField(blank=True, related_name='manage_factories_members', to='users.holding', verbose_name='مدیریت افراد این کارخانه ها'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manage_holdings_members',
            field=models.ManyToManyField(blank=True, related_name='manage_holdings_members', to='users.holding', verbose_name='مدیریت افراد این هلدینگ ها'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manage_sub_employees',
            field=models.BooleanField(default=False, verbose_name='مجوز مدیریت پرسنل زیر مجموعه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manage_subdepartments_members',
            field=models.ManyToManyField(blank=True, related_name='manage_subdepartments_members', to='users.holding', verbose_name='مدیریت افراد این زیر بخش ها'),
        ),
    ]
