# Generated by Django 5.2.6 on 2026-03-30 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_employee_manage_departments_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='center_of_charge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مرکز هزینه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manage_special_employees',
            field=models.ManyToManyField(blank=True, related_name='managed_special_employees', to=settings.AUTH_USER_MODEL, verbose_name='مدیریت کارکنان ویژه'),
        ),
    ]
