# Generated by Django 5.2.6 on 2026-04-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_employee_center_of_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_reserve_for_others1',
            field=models.PositiveSmallIntegerField(choices=[(0, 'اجازه ندارد'), (1, 'مجاز (با محدودیت)'), (2, 'مجاز (بدن محدودیت پسنل مقصد)')], default=0, verbose_name='مجوز رزرو برای دیگران'),
        ),
        migrations.AddField(
            model_name='employee',
            name='factory_limit_reservation',
            field=models.IntegerField(default=1, verbose_name='محدودیت رزرو سهمیه ای'),
        ),
        migrations.AddField(
            model_name='employee',
            name='free_limit_reservation',
            field=models.IntegerField(default=5, verbose_name='محدودیت رزرو آزاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='guest_limit_reservation',
            field=models.IntegerField(default=0, verbose_name='محدودیت رزرو مهمان'),
        ),
    ]
