# Generated by Django 5.2.6 on 2026-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_employee_can_reserve_for_others1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='can_reserve_for_others1',
        ),
        migrations.AlterField(
            model_name='employee',
            name='can_reserve_for_others',
            field=models.PositiveSmallIntegerField(choices=[(0, 'اجازه ندارد'), (1, 'مجاز (با محدودیت)'), (2, 'مجاز (بدن محدودیت پسنل مقصد)')], default=0, verbose_name='مجوز رزرو برای دیگران'),
        ),
    ]
