# Generated by Django 5.2.6 on 2026-04-06 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_remove_employee_can_reserve_for_others1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manage_departments_members',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manage_factories_members',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manage_holdings_members',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manage_special_employees',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manage_subdepartments_members',
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_accessible_departments',
            field=models.ManyToManyField(blank=True, related_name='hr_accessible_by', to='users.department', verbose_name='بخش های قابل مدیریت'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_accessible_employees',
            field=models.ManyToManyField(blank=True, related_name='hr_accessible_by', to=settings.AUTH_USER_MODEL, verbose_name='پرسنل قابل مدیریت'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_accessible_factories',
            field=models.ManyToManyField(blank=True, related_name='hr_accessible_by', to='users.factory', verbose_name='کارخانه های قابل مدیریت'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_accessible_holdings',
            field=models.ManyToManyField(blank=True, related_name='hr_accessible_by', to='users.holding', verbose_name='هلدینگ های قابل مدیریت'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hr_accessible_subdepartments',
            field=models.ManyToManyField(blank=True, related_name='hr_accessible_by', to='users.subdepartment', verbose_name='زیر بخش های قابل مدیریت'),
        ),
    ]
