# Generated by Django 5.2.6 on 2026-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_employee_can_reserve_for_which_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
