# Generated by Django 5.2.6 on 2026-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_employee_is_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_contractor',
            field=models.BooleanField(default=False, verbose_name='آیا پیمانکار است؟'),
        ),
    ]
