# Generated by Django 5.2.6 on 2026-04-21 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_alter_employee_is_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hr_granting_role_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='حد اعطای نقش به پرسنل مربوطه'),
        ),
    ]
