# Generated by Django 5.2.6 on 2026-05-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_employee_hr_granting_role_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_permision',
            field=models.PositiveSmallIntegerField(choices=[(0, 'بدون مجزو'), (1, 'گزارش گیری سلف')], default=0, verbose_name='مجوز گزارش گیری'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='day_persian',
            field=models.CharField(choices=[('shanbe', 'شنبه'), ('1shanbe', 'یکشنبه'), ('2shanbe', 'دوشنبه'), ('3shanbe', 'سه شنبه'), ('4shanbe', 'چهارشنبه'), ('5shanbe', 'پنج شنبه'), ('jome', 'جمعه')], max_length=10, verbose_name='روز هفته'),
        ),
    ]
