# Generated by Django 5.2.6 on 2026-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_employee_reporting_permision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login_required',
            field=models.BooleanField(default=False, verbose_name='نیاز به لاگین مجدد'),
        ),
    ]
