# Generated by Django 5.2.6 on 2026-05-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_employee_extra_available_factories_for_food_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='extra_available_factories_for_food_reservation',
            field=models.ManyToManyField(blank=True, null=True, related_name='extra_employee_for_food_reservation', to='users.factory', verbose_name='کارخانه های اضافه مجاز به رزرو غذا'),
        ),
    ]
