# Generated by Django 5.2.6 on 2026-05-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_alter_employee_extra_available_factories_for_food_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='karimax_permision',
            field=models.BooleanField(default=True),
        ),
    ]
