# Generated by Django 5.2.6 on 2026-06-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_userpasskey'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
