# Generated by Django 5.2.6 on 2026-06-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_alter_employee_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Place_of_service_recruitment_order',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='محل خدمت حکم کارگزین'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Position_Job_history',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سمت سوابق شغلی'),
        ),
    ]
