# Generated by Django 5.2.6 on 2026-06-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_employee_place_of_service_recruitment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='item_type',
            field=models.CharField(choices=[('performance_file', 'ارسال فایل عملکرد'), ('work_experience', 'ارسال تجربیات کاری'), ('meeting_minutes', 'صورت جلسات'), ('suggestions', 'پیشنهادات'), ('critiques', 'انتقادات'), ('learning', 'آموزش')], max_length=50, verbose_name='نوع ایتم'),
        ),
    ]
