# Generated by Django 5.2.6 on 2026-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0111_alter_participation_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_create_notification',
            field=models.BooleanField(default=False, verbose_name='مجوز ساخت اعلان'),
        ),
    ]
