# Generated by Django 5.2.6 on 2026-06-29 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_employee_can_create_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('work', 'عملیاتی'), ('production', 'تولید'), ('maintenance', 'نگهداری و تعمیرات'), ('quality', 'کنترل کیفیت'), ('cultural', 'فرهنگی / اطلاع\u200cرسانی'), ('celebration', 'تبریک و مناسبت'), ('safety', 'ایمنی'), ('hr', 'منابع انسانی'), ('general', 'عمومی')], default='general', max_length=30, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('critical', 'حیاتی'), ('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین'), ('info', 'اطلاع\u200cرسانی')], default='medium', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
