# Generated by Django 5.2.6 on 2026-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_notification_category_notification_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('critical', 'حیاتی'), ('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین')], default='medium', max_length=20, verbose_name='اولویت'),
        ),
    ]
