# Generated by Django 5.2.6 on 2026-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0116_backgroundjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='users_backg_job_id_0f8173_idx',
            old_name='users_back_job_id_8b9d9c_idx',
        ),
        migrations.AlterField(
            model_name='participation',
            name='manager_2_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('waiting', 'در صف پردازش'), ('running', 'در حال پردازش'), ('retrying', 'در حال تلاش مجدد'), ('success', 'موفق'), ('failed', 'ناموفق'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت مدیر کمیته 2'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='manager_3_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('waiting', 'در صف پردازش'), ('running', 'در حال پردازش'), ('retrying', 'در حال تلاش مجدد'), ('success', 'موفق'), ('failed', 'ناموفق'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت مدیر کمیته 3'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='manager_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('waiting', 'در صف پردازش'), ('running', 'در حال پردازش'), ('retrying', 'در حال تلاش مجدد'), ('success', 'موفق'), ('failed', 'ناموفق'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت مدیر کمیته 1'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('waiting', 'در صف پردازش'), ('running', 'در حال پردازش'), ('retrying', 'در حال تلاش مجدد'), ('success', 'موفق'), ('failed', 'ناموفق'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='supervisor_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('waiting', 'در صف پردازش'), ('running', 'در حال پردازش'), ('retrying', 'در حال تلاش مجدد'), ('success', 'موفق'), ('failed', 'ناموفق'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت سرپرست کمیته'),
        ),
    ]
