# Generated by Django 5.2.6 on 2026-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_backgroundjob_operational_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_department_managers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_employees',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_factory_managers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_holding_managers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_subdepartment_supervisors',
            field=models.BooleanField(default=True),
        ),
    ]
