# Generated by Django 5.2.6 on 2026-07-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_notification_notify_department_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_department_managers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_factory_managers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_holding_managers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_subdepartment_supervisors',
            field=models.BooleanField(default=False),
        ),
    ]
