# Generated by Django 5.2.6 on 2026-07-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_alter_notification_notify_department_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notification_accessible_departments',
            field=models.ManyToManyField(blank=True, related_name='notification_accessible_by', to='users.department', verbose_name='بخش\u200cهای مجاز برای ایجاد اعلان'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notification_accessible_factories',
            field=models.ManyToManyField(blank=True, related_name='notification_accessible_by', to='users.factory', verbose_name='کارخانه\u200cهای مجاز برای ایجاد اعلان'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notification_accessible_holdings',
            field=models.ManyToManyField(blank=True, related_name='notification_accessible_by', to='users.holding', verbose_name='هلدینگ\u200cهای مجاز برای ایجاد اعلان'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notification_accessible_subdepartments',
            field=models.ManyToManyField(blank=True, related_name='notification_accessible_by', to='users.subdepartment', verbose_name='زیربخش\u200cهای مجاز برای ایجاد اعلان'),
        ),
    ]
