# Generated by Django 5.2.6 on 2025-09-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='فیدبک رد شدن'),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='تأیید نهایی کاربر'),
        ),
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر'), ('super_admin_review', 'در انتظار تأیید مدیر کل'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='participation',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='متن استخراج\u200cشده'),
        ),
    ]
