# Generated by Django 5.2.6 on 2025-10-21 10:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_participation_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='summarized_content',
            field=models.TextField(blank=True, null=True, verbose_name='محتوای خلاصه شده'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='attachment',
            field=models.FileField(default='nothing', upload_to=users.models.participation_upload_path, verbose_name='پیوست'),
            preserve_default=False,
        ),
    ]
