# Generated by Django 5.2.6 on 2025-10-28 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_employee_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(related_name='employees', to='users.role', verbose_name='نقش\u200cها'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام هلدینگ')),
                ('location', models.CharField(max_length=200, verbose_name='مکان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_holdings', to=settings.AUTH_USER_MODEL, verbose_name='مدیر هلدینگ')),
            ],
            options={
                'verbose_name': 'هلدینگ',
                'verbose_name_plural': 'هلدینگ\u200cها',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.holding', verbose_name='هلدینگ'),
        ),
        migrations.AddField(
            model_name='factory',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factories', to='users.holding', verbose_name='هلدینگ'),
        ),
        migrations.CreateModel(
            name='Subdepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیربخش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartments', to='users.department', verbose_name='بخش')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_subdepartments', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست زیربخش')),
            ],
            options={
                'verbose_name': 'زیربخش',
                'verbose_name_plural': 'زیربخش\u200cها',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.subdepartment', verbose_name='زیربخش'),
        ),
    ]
