# Generated by Django 5.2.6 on 2025-11-15 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_employee_department_remove_employee_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='کمیته است؟'),
        ),
        migrations.AddField(
            model_name='department',
            name='linked_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department', verbose_name='کارخانه لینک شده'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_managed_departments_2', to=settings.AUTH_USER_MODEL, verbose_name='مدیر دوم'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_managed_departments_3', to=settings.AUTH_USER_MODEL, verbose_name='مدیر سوم'),
        ),
        migrations.AddField(
            model_name='factory',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='کمیته است؟'),
        ),
        migrations.AddField(
            model_name='factory',
            name='linked_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.factory', verbose_name='کارخانه لینک شده'),
        ),
        migrations.AddField(
            model_name='participation',
            name='department_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_department_participations', to='users.department', verbose_name='بخش کمیته مرتبط'),
        ),
        migrations.AddField(
            model_name='participation',
            name='factory_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_factory_participations', to='users.factory', verbose_name='کارخانه کمیته مرتبط'),
        ),
        migrations.AddField(
            model_name='participation',
            name='holding_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_participations', to='users.holding', verbose_name='هلدینگ کمیته مرتبط'),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='کمیته است؟'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_2_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='نظر مدیر دوم'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_2_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت مدیر کمیته 2'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_3_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='نظر مدیر سوم'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_3_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت مدیر کمیته 3'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='نظر مدیر اول'),
        ),
        migrations.AddField(
            model_name='participation',
            name='manager_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت مدیر کمیته 1'),
        ),
        migrations.AddField(
            model_name='participation',
            name='subdepartment_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_subdepartment_participations', to='users.subdepartment', verbose_name='زیربخش کمیته مرتبط'),
        ),
        migrations.AddField(
            model_name='participation',
            name='supervisor_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='نظر سرپرست'),
        ),
        migrations.AddField(
            model_name='participation',
            name='supervisor_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], max_length=30, null=True, verbose_name='وضعیت سرپرست کمیته'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='کمیته است؟'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='linked_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subdepartment', verbose_name='کارخانه لینک شده'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_participations', to='users.department', verbose_name='بخش مرتبط'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_participations', to='users.factory', verbose_name='کارخانه مرتبط'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='users.holding', verbose_name='هلدینگ مرتبط'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('user_review', 'در انتظار بررسی کاربر'), ('supervisor_review', 'در انتظار تأیید سرپرست'), ('manager_review', 'در انتظار تأیید مدیر بخش'), ('factory_manager_review', 'در انتظار تأیید مدیر کارخانه'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartment_participations', to='users.subdepartment', verbose_name='زیربخش مرتبط'),
        ),
    ]
