# Generated by Django 5.2.6 on 2025-11-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_department_is_committee_department_linked_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartment',
            name='linked_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.factory', verbose_name='کارخانه لینک شده'),
        ),
    ]
