# Generated by Django 5.2.6 on 2025-11-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='feedback',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='نظر و پیشنهاد'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='امتیاز (۱ تا ۵ ستاره)'),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_audio',
            field=models.BooleanField(default=False, verbose_name='فایل قابل تبدیل به متن است؟'),
        ),
        migrations.AddField(
            model_name='participation',
            name='return_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دفعات برگردانده  شده'),
        ),
    ]
