# Generated by Django 5.2.6 on 2025-12-11 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_default_price_fooditem_factory_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('holding', 'هلدینگ'), ('factory', 'کارخانه'), ('department', 'بخش'), ('subdepartment', 'زیربخش')], max_length=20)),
                ('path_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.factory')),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.holding')),
                ('subdepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_by_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.role')),
                ('created_by_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_referrals', to='users.orgunit')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('final_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_referrals', to='users.orgunit')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='users.participation')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(null=True)),
                ('order', models.PositiveIntegerField()),
                ('from_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_steps', to='users.role')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_steps', to='users.orgunit')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_referral_steps', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='users.referral')),
                ('to_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_steps', to='users.role')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_steps', to='users.orgunit')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_referral_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('referral', 'order')},
            },
        ),
    ]
