# Generated by Django 5.2.6 on 2025-12-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_employee_unlimit_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_factories',
            field=models.ManyToManyField(blank=True, null=True, related_name='targeted_notifications', to='users.factory', verbose_name='کارخانه\u200cهای هدف (از هلدینگ\u200cهای انتخابی)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_holdings',
            field=models.ManyToManyField(blank=True, null=True, related_name='targeted_notifications', to='users.holding', verbose_name='هلدینگ\u200cهای هدف (فقط هلدینگ\u200cهای مجاز)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='targeted_notifications', to='users.role', verbose_name='نقش\u200cهای هدف (چه کسانی ببینند)'),
        ),
    ]
