# Generated by Django 5.2.6 on 2025-12-24 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_notification_target_factories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد نوع حساب')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع حساب بانکی')),
            ],
            options={
                'verbose_name': 'نوع حساب بانکی',
                'verbose_name_plural': 'نوع حساب های بانکی',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد بانک')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام بانک')),
            ],
            options={
                'verbose_name': 'بانک',
                'verbose_name_plural': 'بانک ها',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد کشور')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام کشور')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DependencyStatus',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد وضعیت')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام وضعیت تکفل')),
            ],
            options={
                'verbose_name': 'وضعیت تکفل',
                'verbose_name_plural': 'وضعیت\u200cهای تکفل',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد نوع استخدام')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام نوع استخدام')),
            ],
            options={
                'verbose_name': 'نوع استخدام',
                'verbose_name_plural': 'انواع استخدام',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد جنسیت')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'جنسیت',
                'verbose_name_plural': 'جنسیت\u200cها',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد نوع بیمه')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام نوع بیمه')),
            ],
            options={
                'verbose_name': 'نوع بیمه تکمیلی',
                'verbose_name_plural': 'انواع بیمه تکمیلی',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد گروه شغلی')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان گروه شغلی')),
            ],
            options={
                'verbose_name': 'گروه شغلی',
                'verbose_name_plural': 'گروه\u200cهای شغلی',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد وضعیت')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام وضعیت تاهل')),
            ],
            options={
                'verbose_name': 'وضعیت تاهل',
                'verbose_name_plural': 'وضعیت\u200cهای تاهل',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RelativeType',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد نسبت')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام نسبت')),
            ],
            options={
                'verbose_name': 'نسبت با بیمه\u200cشده',
                'verbose_name_plural': 'نسبت\u200cهای خانوادگی',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dependency_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.dependencystatus', verbose_name='وضعیت تکفل'),
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=50, verbose_name='نام پدر')),
                ('birth_certificate_number', models.CharField(max_length=50, verbose_name='شماره شناسنامه')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.country', verbose_name='کشور')),
                ('dependency_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.dependencystatus', verbose_name='وضعیت تکفل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to=settings.AUTH_USER_MODEL, verbose_name='کارمند اصلی')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.gender', verbose_name='جنسیت')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.maritalstatus', verbose_name='وضعیت تأهل')),
                ('relative_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.relativetype', verbose_name='نسبت')),
            ],
            options={
                'verbose_name': 'وابسته',
                'verbose_name_plural': 'وابستگان',
                'unique_together': {('employee', 'national_id')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.gender', verbose_name='جنسیت'),
        ),
        migrations.CreateModel(
            name='Employee_Bimeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimeh_nubmer', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بیمه')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.country', verbose_name='کشور')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bimeh', to=settings.AUTH_USER_MODEL, verbose_name='کارمند اصلی')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.employmenttype', verbose_name='نوع استخدام')),
                ('insurance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.insurancetype', verbose_name='نوع بیمه')),
                ('job_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.jobgroup', verbose_name='گروه شغلی')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.maritalstatus', verbose_name='وضعیت تأهل'),
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
                ('dependent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to='users.dependent', verbose_name='وابسته')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره\u200cهای تماس',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('dependent__isnull', True)), models.Q(('employee__isnull', True), ('dependent__isnull', False)), _connector='OR'), name='contactinfo_one_owner_only')],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('ir', models.CharField(default='ir', editable=False, max_length=2, verbose_name='ir')),
                ('sheba_number', models.CharField(blank=True, max_length=26, null=True, unique=True, verbose_name='شماره شبا')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
                ('bank_account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.bankaccounttype', verbose_name='نوع حساب بانکی')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.banks', verbose_name='بانک')),
                ('dependent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.dependent', verbose_name='وابسته')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('dependent__isnull', True)), models.Q(('employee__isnull', True), ('dependent__isnull', False)), _connector='OR'), name='bankaccount_one_owner_only')],
            },
        ),
    ]
