# Generated by Django 5.2.6 on 2025-12-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_baseinsurance_employee_bimeh_base_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousInsurer',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد بیمه گر قبلی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام بیمه گر قبلی')),
            ],
            options={
                'verbose_name': 'بیمه گر قبلی',
                'verbose_name_plural': 'بیمه گران قبلی',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='employee_bimeh',
            name='insurance_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='employee_bimeh',
            name='coverage_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت پوشش (ماه)'),
        ),
        migrations.AddField(
            model_name='employee_bimeh',
            name='previous_insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.previousinsurer', verbose_name='بیمه گر قبلی'),
        ),
        migrations.DeleteModel(
            name='InsuranceType',
        ),
    ]
