# Generated by Django 5.2.6 on 2025-12-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_previousinsurer_remove_employee_bimeh_insurance_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobgroup',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=10, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.banks', verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='شماره شبا'),
        ),
    ]
