# Generated by Django 5.2.6 on 2025-12-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=26, null=True, unique=True, verbose_name='شماره شبا'),
        ),
    ]
