# Generated by Django 5.2.6 on 2026-01-15 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_bankaccount_sheba_number_alter_fooditem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.country', verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.gender', verbose_name='جنسیت'),
        ),
    ]
