# Generated by Django 5.2.6 on 2026-04-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_employee_can_reserve_for_which_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hr_granting_role_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='حد اعطای نقش به پرسنل مربوطه'),
        ),
    ]
