# Generated by Django 5.2.6 on 2026-05-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_employee_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extra_available_factories_for_food_reservation',
            field=models.ManyToManyField(blank=True, null=True, related_name='extra_employee_for_food_reservation', to='users.factory', verbose_name='کارخانه های مجاز به رزرو غذا اضافه'),
        ),
    ]
