# Generated by Django 4.2.7 on 2025-09-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_can_access_all_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_access_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
