# Generated by Django 5.2.6 on 2025-09-26 05:06

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('performance_file', 'ارسال فایل عملکرد'), ('work_experience', 'ارسال تجربیات کاری'), ('meeting_minutes', 'صورت جلسات'), ('suggestions', 'پیشنهادات'), ('critiques', 'انتقادات')], max_length=50, verbose_name='نوع ایتم')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('attachment', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='F:/laragon/www/pmss/media/participations/'), upload_to='participations/', verbose_name='پیوست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'مشارکت',
                'verbose_name_plural': 'مشارکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
