# Generated by Django 5.2.6 on 2025-10-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_participation_orginal_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='count_sumerized',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد دفعات خلاصه شده'),
        ),
    ]
