# Generated by Django 5.2.6 on 2025-11-16 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_subdepartment_linked_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='linked_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.factory', verbose_name='کارخانه لینک شده'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_managed_departments_2', to=settings.AUTH_USER_MODEL, verbose_name='مدیر دوم (کمیته)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_managed_departments_3', to=settings.AUTH_USER_MODEL, verbose_name='مدیر سوم (کمیته)'),
        ),
    ]
