# Generated by Django 5.2.6 on 2025-11-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_department_linked_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Personnel_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='کد پرسنلی'),
        ),
    ]
