# Generated by Django 5.2.6 on 2025-12-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_employee_food_receiver_factory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='default_price',
            new_name='factory_price',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='real_price',
            new_name='free_price',
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='is_quota_used',
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='guest_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت غذای مهمان'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='factory_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت کارخانه'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='factory_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد غذا به قیمت کارخانه'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='free_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت آزاد'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='free_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد غذا به قیمت آزاد'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='guest_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت غذای مهمان'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='guest_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد غذای مهمان'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه کل این سفارش'),
        ),
    ]
