# Generated by Django 5.2.6 on 2025-12-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_bankaccounttype_banks_country_dependencystatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInsurance',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='کد بیمه گر پایه')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام بیمه گر پایه')),
            ],
            options={
                'verbose_name': 'بیمه گر پایه',
                'verbose_name_plural': 'بیمه گران پایه',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='employee_bimeh',
            name='base_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.baseinsurance', verbose_name='بیمه گر پایه'),
        ),
    ]
