# Generated by Django 5.2.6 on 2026-01-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_dependent_birth_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='factory_bimeh',
            field=models.BooleanField(default=False, verbose_name='اجازه دانلود اطلاعات بیمه ای پرسنل کارخانه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='holding_bimeh',
            field=models.BooleanField(default=False, verbose_name='اجازه دانلود اطلاعات بیمه ای پرسنل هلدینگ'),
        ),
    ]
