# Generated by Django 5.2.6 on 2026-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_management_food',
            field=models.BooleanField(default=False, verbose_name='غذای مدریتی'),
        ),
    ]
