# Generated by Django 5.2.6 on 2026-02-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_employee_can_reserve_for_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='close_food_res_time_H',
            field=models.IntegerField(default=10, verbose_name='ساعت بسته شدن مهلت رزرو غذا در این کارخانه'),
        ),
        migrations.AddField(
            model_name='factory',
            name='close_food_res_time_M',
            field=models.IntegerField(default=0, verbose_name='دقیقه بسته شدن مهلت رزرو غذا در این کارخانه'),
        ),
    ]
