# Generated by Django 5.2.6 on 2026-04-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_remove_employee_manage_departments_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_reserve_for_which_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'فقط همان روز'), (1, 'مجاز به رزرو برای اینده و گذشته')], default=0, verbose_name='مجوز رزرو برای تاریخ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_contractor',
            field=models.BooleanField(default=False, verbose_name='آیا پیمانکار است؟'),
        ),
    ]
